sudo: false
language: node_js
cache:
  yarn: true
  directories:
  - node_modules
env:
  - NODE_ENV=development
matrix:
  fast_finish: true
install:
  - NODE_ENV=development yarn install
script:
  - yarn lint
  - yarn test -- --runInBand
  - if [ "${NODE_ENV}" = "development" ]; then yarn coverage; fi
